project:
  type: book
  output-dir: docs

book:
  title: "An Introduction to Zig"
  author: "Pedro Duarte Faria"
  date: "today"
  chapters:
    - index.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo



