project:
  type: book
  output-dir: docs

book:
  title: "An Introduction to Zig"
  author: "Pedro Duarte Faria"
  date: "today"
  cover-image: "Cover/cover-artv2.1.png"
  chapters:
    - index.qmd
    - Chapters/01-zig-weird.qmd
    - Chapters/01-memory.qmd
    - Chapters/01-base64.qmd
    - Chapters/02-debugging.qmd
    - references.qmd

bibliography: references.bib
execute:
  freeze: auto

format:
  html:
    theme: cosmo
  # pdf:
  #   pdf-engine: xelatex



