project:
  type: book
  output-dir: docs

book:
  title: "An Introduction to Zig"
  author: "Pedro Duarte Faria"
  date: "today"
  cover-image: "Cover/cover-artv2.1.png"
  chapters:
    - index.qmd
    - Chapters/01-zig-weird.qmd
    - Chapters/01-memory.qmd
    - Chapters/01-base64.qmd
    - Chapters/02-debugging.qmd
    - Chapters/05-pointers.qmd
    - Chapters/04-http-server.qmd
    - Chapters/03-unittests.qmd
    - Chapters/07-build-system.qmd
    - Chapters/09-error-handling.qmd
    - references.qmd

bibliography: references.bib
execute:
  freeze: auto


highlight-style: github
format:
  html:
    theme:
      light: cosmo
      dark: darkly
  # pdf:
  #   pdf-engine: xelatex



